### ISSUE TITLE
Can you please add a license file?

### ISSUE THREAD

**Issue by patrickms** [triska/rits#2]
I am considering using your code in another project, but whether I can do it depends on the license. If it's Apache/MIT/BSD (2 or 3 clause) then I can use it. If it's GPL or another strong copyleft license, then I can't (LGPL is a marginal case). Can you please add a license file clarifying the licensing terms?

**Comment by triska** [comment]
Done: It's MIT.

Good luck with your project, I hope this helps!

**Comment by patrickms** [comment]
Thank you very much.
